name: flutter_dialogs
description: Collection of dialog with advanced style and controlling system.
version: 0.0.2
homepage: https://github.com/P-YMR/flutter_dialogs.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: